import { OrderDirectoryEntry } from '../../../pedidos';
import { CreditActorEntry } from '../../credit.types';
import { CreditApplication } from '../../domain/entities/credit-application.entity';
import { CreditActorNotFoundError, CreditCompanyRequiredError, CreditForbiddenError, CreditOrderInvalidError, CreditPolicyInactiveError, CreditValidationError } from '../../domain/errors/credit.errors';
import { CreditActorDirectoryPort } from '../../domain/ports/credit-actor-directory.port';
import { CreditPolicyEntry, CreditRequirementSnapshot } from '../../domain/ports/credit.repositories';
import { CreditMoney } from '../../domain/value-objects/credit-money.vo';
export async function requireCreditActor(users:CreditActorDirectoryPort,actorId:number):Promise<CreditActorEntry & {empresaId:number}>{const a=await users.findById(actorId);if(!a||!a.activo)throw new CreditActorNotFoundError(actorId);if(!a.empresaId)throw new CreditCompanyRequiredError(actorId);return a as CreditActorEntry & {empresaId:number};}
export function readScope(actor:CreditActorEntry & {empresaId:number}){return{empresaId:actor.empresaId,...(actor.rol==='VENDEDOR'?{vendedorId:actor.id}:{}),role:actor.rol};}
export function assertDraftWriter(actor:CreditActorEntry){if(!['ADMIN','VENDEDOR','BODEGA'].includes(actor.rol))throw new CreditForbiddenError('Solo ADMIN, VENDEDOR o BODEGA pueden preparar solicitudes de crédito.');}
export function assertReviewer(actor:CreditActorEntry){if(!actor.rol==='ADMIN')throw new CreditForbiddenError('Solo ADMIN puede revisar o resolver crédito.');}
export function assertOrderForCredit(order:OrderDirectoryEntry,actor:CreditActorEntry & {empresaId:number}){if(order.empresaId!==actor.empresaId)throw new CreditForbiddenError();if(!['CREDITO','MIXTO'].includes(order.condicionPago))throw new CreditOrderInvalidError('El pedido no requiere evaluación de crédito.',{condicionPago:order.condicionPago});if(order.estado!=='PENDIENTE_VALIDACION')throw new CreditOrderInvalidError('El pedido debe estar PENDIENTE_VALIDACION para tramitar crédito.',{estado:order.estado});if(actor.rol==='VENDEDOR'&&order.vendedorId!==actor.id)throw new CreditForbiddenError('Un vendedor solo puede gestionar crédito de sus propios pedidos.');}
export function assertApplicationAccess(actor:CreditActorEntry & {empresaId:number},application:CreditApplication,order:OrderDirectoryEntry){if(application.empresaId!==actor.empresaId||order.empresaId!==actor.empresaId)throw new CreditForbiddenError();if(actor.rol==='VENDEDOR'&&order.vendedorId!==actor.id)throw new CreditForbiddenError('Un vendedor solo puede consultar y editar crédito de sus propios pedidos.');}
export function validateAgainstOrder(order:OrderDirectoryEntry,monto:string){const requested=CreditMoney.from(monto),total=CreditMoney.from(order.total);if(!requested.equals(total))throw new CreditValidationError('El monto solicitado debe coincidir con el total vigente del pedido. El anticipo se representa por separado en pedidos MIXTO.',{montoSolicitado:requested.toString(),pedidoTotal:total.toString(),condicionPago:order.condicionPago});}
export function validateAdvanceForOrder(order:OrderDirectoryEntry,anticipo:string){const advance=CreditMoney.from(anticipo);if(order.condicionPago==='CREDITO'&&!advance.isZero())throw new CreditValidationError('Un pedido CREDITO no debe registrar anticipo; usa condicionPago MIXTO cuando exista anticipo.',{anticipo:advance.toString()});if(order.condicionPago==='MIXTO'&&advance.isZero())throw new CreditValidationError('Un pedido MIXTO requiere un anticipo mayor que cero.',{anticipo:advance.toString()});}
export function validatePolicy(policy:CreditPolicyEntry|null, input:{monto:string;plazoDias:number;anticipo:string}){if(!policy)return;if(!policy.activo)throw new CreditPolicyInactiveError(policy.id);const amount=CreditMoney.from(input.monto),advance=CreditMoney.from(input.anticipo);if(policy.montoMaximo&&amount.isGreaterThan(CreditMoney.from(policy.montoMaximo)))throw new CreditValidationError('El monto solicitado supera el máximo permitido por la política.',{politicaId:policy.id,montoMaximo:policy.montoMaximo});if(policy.plazoMaximoDias&&input.plazoDias>policy.plazoMaximoDias)throw new CreditValidationError('El plazo solicitado supera el máximo permitido por la política.',{politicaId:policy.id,plazoMaximoDias:policy.plazoMaximoDias});if(policy.porcentajeAnticipo){const min=amount.multiplyPercent(policy.porcentajeAnticipo);if(advance.isLessThan(min))throw new CreditValidationError('El anticipo propuesto es menor al mínimo de la política.',{politicaId:policy.id,anticipoMinimo:min.toString()});}}
export function snapshots(policy:CreditPolicyEntry|null):CreditRequirementSnapshot[]{return policy?policy.requisitos.filter(r=>r.activo).map(r=>({politicaRequisitoId:r.id,codigo:r.codigo,nombre:r.nombre,descripcion:r.descripcion,obligatorio:r.obligatorio,orden:r.orden})):[];}
