import { OrderDirectoryPort } from '../../../pedidos';
import { CreditDocumentState, CreditDocumentType, CreditReferenceResult, CreditReferenceType, CreditRequirementState } from '../../credit.types';
import { CreditApplicationNotFoundError, CreditForbiddenError, CreditOrderInvalidError } from '../../domain/errors/credit.errors';
import { CreditActorDirectoryPort } from '../../domain/ports/credit-actor-directory.port';
import { CreditApplicationRepositoryPort, CreditEvidenceRepositoryPort } from '../../domain/ports/credit.repositories';
import { assertApplicationAccess, assertDraftWriter, assertReviewer, requireCreditActor } from './credit.helpers';
export class CreditEvidenceCommands{
 constructor(private readonly apps:CreditApplicationRepositoryPort,private readonly evidence:CreditEvidenceRepositoryPort,private readonly users:CreditActorDirectoryPort,private readonly orders:OrderDirectoryPort){}
 private async context(id:number,actorId:number){const actor=await requireCreditActor(this.users,actorId);const app=await this.apps.findById(id);if(!app)throw new CreditApplicationNotFoundError(id);const order=await this.orders.findById(app.pedidoId);if(!order)throw new CreditForbiddenError();assertApplicationAccess(actor,app,order);return{actor,app};}
 async addReference(id:number,input:{tipo:CreditReferenceType;nombre:string;telefono:string;relacion?:string|null;observaciones?:string|null},actorId:number){const{actor,app}=await this.context(id,actorId);assertDraftWriter(actor);app.assertEvidenceEditable();return this.evidence.addReference({solicitudId:id,...input,audit:{actorId:actor.id,tipo:'REFERENCIA_AGREGADA',detalle:'Referencia agregada al expediente.'}});}
 async updateReference(id:number,referenciaId:number,input:{nombre?:string;telefono?:string;relacion?:string|null;observaciones?:string|null},actorId:number){const{actor,app}=await this.context(id,actorId);assertDraftWriter(actor);app.assertEvidenceEditable();return this.evidence.updateReference({solicitudId:id,referenciaId,...input,audit:{actorId:actor.id,tipo:'REFERENCIA_ACTUALIZADA',detalle:'Referencia actualizada.',referencia:{tipo:'REFERENCIA_CREDITO',id:referenciaId}}});}
 async reviewReference(id:number,referenciaId:number,resultado:Exclude<CreditReferenceResult,'PENDIENTE'>,observaciones:string|null|undefined,actorId:number){const{actor,app}=await this.context(id,actorId);assertReviewer(actor);app.assertReviewable();return this.evidence.reviewReference({solicitudId:id,referenciaId,resultado,observaciones,actorId:actor.id,audit:{actorId:actor.id,tipo:'REFERENCIA_VERIFICADA',detalle:`Referencia revisada: ${resultado}.`,referencia:{tipo:'REFERENCIA_CREDITO',id:referenciaId}}});}
 async addDocument(id:number,input:{tipo:CreditDocumentType;url:string;key?:string|null;mimeType?:string|null;size?:number|null;observaciones?:string|null},actorId:number){const{actor,app}=await this.context(id,actorId);assertDraftWriter(actor);app.assertEvidenceEditable();return this.evidence.addDocument({solicitudId:id,...input,audit:{actorId:actor.id,tipo:'DOCUMENTO_AGREGADO',detalle:`Documento ${input.tipo} agregado.`}});}
 async reviewDocument(id:number,documentoId:number,estado:Exclude<CreditDocumentState,'PENDIENTE'>,observaciones:string|null|undefined,actorId:number){const{actor,app}=await this.context(id,actorId);assertReviewer(actor);app.assertReviewable();return this.evidence.reviewDocument({solicitudId:id,documentoId,estado,observaciones,actorId:actor.id,audit:{actorId:actor.id,tipo:estado==='VALIDADO'?'DOCUMENTO_VALIDADO':'DOCUMENTO_RECHAZADO',detalle:`Documento revisado: ${estado}.`,referencia:{tipo:'DOCUMENTO_CREDITO',id:documentoId}}});}
 async reviewRequirement(id:number,requisitoId:number,estado:Exclude<CreditRequirementState,'PENDIENTE'>,observaciones:string|null|undefined,actorId:number){const{actor,app}=await this.context(id,actorId);assertReviewer(actor);app.assertReviewable();return this.evidence.reviewRequirement({solicitudId:id,requisitoId,estado,observaciones,actorId:actor.id,audit:{actorId:actor.id,tipo:'REQUISITO_ACTUALIZADO',detalle:`Requisito revisado: ${estado}.`,referencia:{tipo:'REQUISITO_CREDITO',id:requisitoId}}});}
}
