export const TRANSFER_REPOSITORY = Symbol('TRANSFER_REPOSITORY');
export const TRANSFER_OPERATION_REPOSITORY = Symbol(
  'TRANSFER_OPERATION_REPOSITORY',
);
export const TRANSFER_QUERY = Symbol('TRANSFER_QUERY');
export const TRANSFER_ACTOR_DIRECTORY = Symbol('TRANSFER_ACTOR_DIRECTORY');
export const TRANSFER_DIRECTORY = Symbol('TRANSFER_DIRECTORY');
