export const DELIVERY_REPOSITORY = Symbol('DELIVERY_REPOSITORY');
export const DELIVERY_QUERY = Symbol('DELIVERY_QUERY');
export const DELIVERY_ACTOR_DIRECTORY = Symbol('DELIVERY_ACTOR_DIRECTORY');
export const DELIVERY_EVIDENCE_STORAGE = Symbol('DELIVERY_EVIDENCE_STORAGE');
export const DELIVERY_DIRECTORY = Symbol('DELIVERY_DIRECTORY');
