export const TRACKING_DIRECTORY = Symbol('TRACKING_DIRECTORY');
export const TRACKING_REPOSITORY = Symbol('TRACKING_REPOSITORY');
export const TRACKING_QUERY = Symbol('TRACKING_QUERY');
export const TRACKING_REALTIME = Symbol('TRACKING_REALTIME');
