export const REQUISITION_REPOSITORY = Symbol('REQUISITION_REPOSITORY');
export const REQUISITION_QUERY = Symbol('REQUISITION_QUERY');
export const REQUISITION_CATALOG = Symbol('REQUISITION_CATALOG');
export const REQUISITION_ACTOR_DIRECTORY = Symbol('REQUISITION_ACTOR_DIRECTORY');
export const REQUISITION_DIRECTORY = Symbol('REQUISITION_DIRECTORY');
