export const BODEGA_REPOSITORY = Symbol('BODEGA_REPOSITORY');
export const BODEGA_QUERY = Symbol('BODEGA_QUERY');
export const BODEGA_COMPANY_CONTEXT = Symbol('BODEGA_COMPANY_CONTEXT');
export const BODEGA_USER_DIRECTORY = Symbol('BODEGA_USER_DIRECTORY');
export const BODEGA_OPERATIONAL_DEPENDENCIES = Symbol(
  'BODEGA_OPERATIONAL_DEPENDENCIES',
);
export const BODEGA_DIRECTORY = Symbol('BODEGA_DIRECTORY');
