export const INVENTORY_REPOSITORY = Symbol('INVENTORY_REPOSITORY');
export const INVENTORY_QUERY = Symbol('INVENTORY_QUERY');
export const INVENTORY_PRODUCT_CATALOG = Symbol('INVENTORY_PRODUCT_CATALOG');
export const INVENTORY_USER_DIRECTORY = Symbol('INVENTORY_USER_DIRECTORY');

export const INVENTORY_AVAILABILITY = Symbol('INVENTORY_AVAILABILITY');
export const INVENTORY_OPERATIONS = Symbol('INVENTORY_OPERATIONS');
