export const CREDIT_APPLICATION_REPOSITORY = Symbol('CREDIT_APPLICATION_REPOSITORY');
export const CREDIT_EVIDENCE_REPOSITORY = Symbol('CREDIT_EVIDENCE_REPOSITORY');
export const CREDIT_DECISION_REPOSITORY = Symbol('CREDIT_DECISION_REPOSITORY');
export const CREDIT_INTEGRATION_REPOSITORY = Symbol('CREDIT_INTEGRATION_REPOSITORY');
export const CREDIT_POLICY_REPOSITORY = Symbol('CREDIT_POLICY_REPOSITORY');
export const CREDIT_QUERY = Symbol('CREDIT_QUERY');
export const CREDIT_ACTOR_DIRECTORY = Symbol('CREDIT_ACTOR_DIRECTORY');
export const CREDIT_DIRECTORY = Symbol('CREDIT_DIRECTORY');
export const CREDIT_AUTHORIZATION = Symbol('CREDIT_AUTHORIZATION');

export const CREDIT_PAYMENT_PLAN_REPOSITORY = Symbol('CREDIT_PAYMENT_PLAN_REPOSITORY');
