import { CreditValidationError } from '../errors/credit.errors';
import { CreditMoney } from '../value-objects/credit-money.vo';
export type CreditPolicyRequirementProps=Readonly<{id?:number|null;codigo:string;nombre:string;descripcion?:string|null;obligatorio?:boolean;orden?:number;activo?:boolean}>;
export type CreditPolicyProps=Readonly<{id?:number|null;empresaId:number;nombre:string;descripcion?:string|null;activo?:boolean;montoMaximo?:string|null;plazoMaximoDias?:number|null;porcentajeAnticipo?:string|null;motivoInactivacion?:string|null;inactivadaEn?:Date|null;version?:number;requisitos?:ReadonlyArray<CreditPolicyRequirementProps>;creadoEn?:Date;actualizadoEn?:Date}>;
export class CreditPolicy{
 private constructor(private props:CreditPolicyProps){this.assert();}
 static create(props:Omit<CreditPolicyProps,'id'|'activo'|'version'|'motivoInactivacion'|'inactivadaEn'>){return new CreditPolicy({...props,nombre:req(props.nombre,'nombre'),descripcion:norm(props.descripcion),montoMaximo:props.montoMaximo==null?null:CreditMoney.from(props.montoMaximo).toString(),porcentajeAnticipo:props.porcentajeAnticipo==null?null:pct(props.porcentajeAnticipo),requisitos:normReqs(props.requisitos??[]),activo:true,version:0});}
 static rehydrate(props:CreditPolicyProps){return new CreditPolicy(props);}
 get id(){return this.props.id??null;} get empresaId(){return this.props.empresaId;} get nombre(){return this.props.nombre;} get descripcion(){return this.props.descripcion??null;} get activo(){return this.props.activo??true;} get montoMaximo(){return this.props.montoMaximo??null;} get plazoMaximoDias(){return this.props.plazoMaximoDias??null;} get porcentajeAnticipo(){return this.props.porcentajeAnticipo??null;} get motivoInactivacion(){return this.props.motivoInactivacion??null;} get inactivadaEn(){return this.props.inactivadaEn??null;} get version(){return this.props.version??0;} get requisitos(){return this.props.requisitos??[];}
 update(i:{nombre?:string;descripcion?:string|null;montoMaximo?:string|null;plazoMaximoDias?:number|null;porcentajeAnticipo?:string|null;requisitos?:ReadonlyArray<CreditPolicyRequirementProps>}){this.props={...this.props,...(i.nombre!==undefined?{nombre:req(i.nombre,'nombre')}:{}),...(i.descripcion!==undefined?{descripcion:norm(i.descripcion)}:{}),...(i.montoMaximo!==undefined?{montoMaximo:i.montoMaximo==null?null:CreditMoney.from(i.montoMaximo).toString()}:{}),...(i.plazoMaximoDias!==undefined?{plazoMaximoDias:i.plazoMaximoDias}:{}),...(i.porcentajeAnticipo!==undefined?{porcentajeAnticipo:i.porcentajeAnticipo==null?null:pct(i.porcentajeAnticipo)}:{}),...(i.requisitos!==undefined?{requisitos:normReqs(i.requisitos)}:{}),version:this.version+1};this.assert();}
 setActive(active:boolean,reason?:string|null,at=new Date()){if(active){this.props={...this.props,activo:true,motivoInactivacion:null,inactivadaEn:null,version:this.version+1};return;}const r=norm(reason);if(!r||r.length<3)throw new CreditValidationError('Debes indicar un motivo válido para desactivar la política.');this.props={...this.props,activo:false,motivoInactivacion:r,inactivadaEn:at,version:this.version+1};}
 private assert(){if(!Number.isInteger(this.empresaId)||this.empresaId<=0)throw new CreditValidationError('La empresa de la política es inválida.');if(!this.nombre.trim())throw new CreditValidationError('El nombre de la política es obligatorio.');if(this.montoMaximo!==null&&CreditMoney.from(this.montoMaximo).isZero())throw new CreditValidationError('El monto máximo debe ser mayor que cero.');if(this.plazoMaximoDias!==null&&(!Number.isInteger(this.plazoMaximoDias)||this.plazoMaximoDias<=0))throw new CreditValidationError('El plazo máximo debe ser un entero positivo.');if(this.porcentajeAnticipo!==null)pct(this.porcentajeAnticipo);if(!Number.isInteger(this.version)||this.version<0)throw new CreditValidationError('Versión de política inválida.');}
}
function normReqs(rs:ReadonlyArray<CreditPolicyRequirementProps>){const seen=new Set<string>();return rs.map((r,i)=>{const c=req(r.codigo,'codigo').toUpperCase();if(seen.has(c))throw new CreditValidationError('Código de requisito duplicado.',{codigo:c});seen.add(c);return{...r,codigo:c,nombre:req(r.nombre,'nombre'),descripcion:norm(r.descripcion),obligatorio:r.obligatorio??true,orden:r.orden??i,activo:r.activo??true};});}
function pct(v:string|number){const n=Number(v);if(!Number.isFinite(n)||n<0||n>100)throw new CreditValidationError('El porcentaje de anticipo debe estar entre 0 y 100.');return n.toFixed(2);}function norm(v?:string|null){if(v==null)return null;const s=v.trim();return s||null;}function req(v:string,f:string){const s=v.trim();if(!s)throw new CreditValidationError(`El campo ${f} es obligatorio.`);return s;}
