export const DISPATCH_REPOSITORY = Symbol('DISPATCH_REPOSITORY');
export const DISPATCH_OPERATION_REPOSITORY = Symbol('DISPATCH_OPERATION_REPOSITORY');
export const DISPATCH_QUERY = Symbol('DISPATCH_QUERY');
export const DISPATCH_ACTOR_DIRECTORY = Symbol('DISPATCH_ACTOR_DIRECTORY');
export const DISPATCH_DIRECTORY = Symbol('DISPATCH_DIRECTORY');
