export const TRANSPORT_QUERY = Symbol('TRANSPORT_QUERY');
export const TRANSPORT_WORKFLOW = Symbol('TRANSPORT_WORKFLOW');
export const TRANSPORT_CATALOG_REPOSITORY = Symbol(
  'TRANSPORT_CATALOG_REPOSITORY',
);
export const TRANSPORT_ACTOR_DIRECTORY = Symbol('TRANSPORT_ACTOR_DIRECTORY');
export const TRANSPORT_DIRECTORY = Symbol('TRANSPORT_DIRECTORY');
export const TRANSPORT_DELIVERY_GATE = Symbol('TRANSPORT_DELIVERY_GATE');
