export const PAYMENT_ACTOR_DIRECTORY = Symbol('PAYMENT_ACTOR_DIRECTORY');
export const PAYMENT_CONTEXT_DIRECTORY = Symbol('PAYMENT_CONTEXT_DIRECTORY');
export const PAYMENT_WORKFLOW = Symbol('PAYMENT_WORKFLOW');
export const PAYMENT_QUERY = Symbol('PAYMENT_QUERY');
export const PAYMENT_DIRECTORY = Symbol('PAYMENT_DIRECTORY');

export const PAYMENT_BANK_REPOSITORY = Symbol('PAYMENT_BANK_REPOSITORY');
