export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const ORDER_QUERY = Symbol('ORDER_QUERY');
export const ORDER_ACTOR_DIRECTORY = Symbol('ORDER_ACTOR_DIRECTORY');
export const ORDER_CUSTOMER_DIRECTORY = Symbol('ORDER_CUSTOMER_DIRECTORY');
export const ORDER_VISIT_DIRECTORY = Symbol('ORDER_VISIT_DIRECTORY');
export const ORDER_PRODUCT_CATALOG = Symbol('ORDER_PRODUCT_CATALOG');
export const ORDER_DIRECTORY = Symbol('ORDER_DIRECTORY');
export const ORDER_BILLING_DIRECTORY = Symbol('ORDER_BILLING_DIRECTORY');

export const ORDER_CREDIT_GATE = Symbol('ORDER_CREDIT_GATE');
export const ORDER_DISPATCH_GATE = Symbol('ORDER_DISPATCH_GATE');
export const ORDER_DELIVERY_GATE = Symbol('ORDER_DELIVERY_GATE');
