import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from 'src/prisma.service';
import { CreditApplication } from '../../../domain/entities/credit-application.entity';
import { CreditActiveApplicationExistsError, CreditAlreadyDecidedError, CreditConcurrentModificationError, CreditIdempotencyConflictError, CreditValidationError } from '../../../domain/errors/credit.errors';
import { CreditApplicationRepositoryPort, CreditDecisionCommitResult, CreditDecisionRepositoryPort, CreditEvidenceRepositoryPort, CreditIntegrationOperation, CreditIntegrationRepositoryPort, CreditReadiness, CreditRequirementSnapshot } from '../../../domain/ports/credit.repositories';
import { CreditAuditDraft } from '../../../credit.types';

@Injectable()
export class CreditPrismaRepository implements CreditApplicationRepositoryPort,CreditEvidenceRepositoryPort,CreditDecisionRepositoryPort,CreditIntegrationRepositoryPort{
 constructor(private readonly prisma:PrismaService){}
 async findById(id:number){const r=await this.prisma.solicitudCredito.findUnique({where:{id}});return r?this.toApplication(r):null;}
 async findActiveByOrderId(orderId:number){const r=await this.prisma.solicitudCredito.findFirst({where:{pedidoId:orderId,estado:{in:['PENDIENTE','EN_REVISION','APROBADA']}},orderBy:{solicitadaEn:'desc'}});return r?this.toApplication(r):null;}
 async create(entity:CreditApplication,requirements:CreditRequirementSnapshot[],audit:CreditAuditDraft){
  try{
   return await this.prisma.$transaction(async tx=>{const r=await tx.solicitudCredito.create({data:{empresaId:entity.empresaId,pedidoId:entity.pedidoId,clienteId:entity.clienteId,solicitanteId:entity.solicitanteId,politicaId:entity.politicaId,montoSolicitado:new Prisma.Decimal(entity.montoSolicitado),plazoDias:entity.plazoDias,anticipoPropuesto:new Prisma.Decimal(entity.anticipoPropuesto),estado:entity.estado,motivo:entity.motivo,version:entity.version,requisitos:{create:requirements.map(x=>({...x}))}}});await tx.solicitudCredito.update({where:{id:r.id},data:{numero:this.applicationNumber(r.id)}});await this.event(tx,r.id,audit);const p=await tx.solicitudCredito.findUniqueOrThrow({where:{id:r.id}});return this.toApplication(p);});
  }catch(error:any){
   if(error?.code==='P2002')throw new CreditActiveApplicationExistsError(entity.pedidoId);
   throw error;
  }
 }
 async save(entity:CreditApplication,expectedVersion:number,audit:CreditAuditDraft,options?:Readonly<{replaceRequirements?:CreditRequirementSnapshot[]}>){if(!entity.id)throw new Error('Solicitud sin id.');return this.prisma.$transaction(async tx=>{const u=await tx.solicitudCredito.updateMany({where:{id:entity.id,version:expectedVersion},data:{politicaId:entity.politicaId,montoSolicitado:new Prisma.Decimal(entity.montoSolicitado),plazoDias:entity.plazoDias,anticipoPropuesto:new Prisma.Decimal(entity.anticipoPropuesto),estado:entity.estado,motivo:entity.motivo,enRevisionEn:entity.enRevisionEn,resueltaEn:entity.resueltaEn,canceladaEn:entity.canceladaEn,motivoCancelacion:entity.motivoCancelacion,version:entity.version}});if(u.count!==1)throw new CreditConcurrentModificationError({id:entity.id,expectedVersion});if(options?.replaceRequirements){await tx.solicitudCreditoRequisito.deleteMany({where:{solicitudId:entity.id}});if(options.replaceRequirements.length)await tx.solicitudCreditoRequisito.createMany({data:options.replaceRequirements.map(x=>({solicitudId:entity.id!,...x}))});}await this.event(tx,entity.id,audit);const p=await tx.solicitudCredito.findUniqueOrThrow({where:{id:entity.id}});return this.toApplication(p);});}
 async addReference(i:any){return this.prisma.$transaction(async tx=>{await this.assertOpen(tx,i.solicitudId);const r=await tx.referenciaCredito.create({data:{solicitudId:i.solicitudId,tipo:i.tipo,nombre:i.nombre.trim(),telefono:i.telefono.trim(),relacion:this.text(i.relacion),observaciones:this.text(i.observaciones)}});await this.event(tx,i.solicitudId,{...i.audit,referencia:{tipo:'REFERENCIA_CREDITO',id:r.id}});return{id:r.id};});}
 async updateReference(i:any){return this.prisma.$transaction(async tx=>{await this.assertOpen(tx,i.solicitudId);const current=await tx.referenciaCredito.findFirst({where:{id:i.referenciaId,solicitudId:i.solicitudId}});if(!current)throw new CreditValidationError('La referencia no existe en esta solicitud.');if(current.resultado!=='PENDIENTE')throw new CreditValidationError('Una referencia ya revisada no puede editarse.');await tx.referenciaCredito.update({where:{id:i.referenciaId},data:{...(i.nombre!==undefined?{nombre:i.nombre.trim()}:{}),...(i.telefono!==undefined?{telefono:i.telefono.trim()}:{}),...(i.relacion!==undefined?{relacion:this.text(i.relacion)}:{}),...(i.observaciones!==undefined?{observaciones:this.text(i.observaciones)}:{}),version:{increment:1}}});await this.event(tx,i.solicitudId,i.audit);});}
 async reviewReference(i:any){return this.prisma.$transaction(async tx=>{await this.assertReview(tx,i.solicitudId);const u=await tx.referenciaCredito.updateMany({where:{id:i.referenciaId,solicitudId:i.solicitudId},data:{resultado:i.resultado,observaciones:this.text(i.observaciones),verificadoPorId:i.actorId,verificadoEn:new Date(),version:{increment:1}}});if(u.count!==1)throw new CreditValidationError('La referencia no existe en esta solicitud.');await this.event(tx,i.solicitudId,i.audit);});}
 async addDocument(i:any){return this.prisma.$transaction(async tx=>{await this.assertOpen(tx,i.solicitudId);const d=await tx.documentoCredito.create({data:{solicitudId:i.solicitudId,tipo:i.tipo,url:i.url.trim(),key:this.text(i.key),mimeType:this.text(i.mimeType),size:i.size??null,observaciones:this.text(i.observaciones)}});await this.event(tx,i.solicitudId,{...i.audit,referencia:{tipo:'DOCUMENTO_CREDITO',id:d.id}});return{id:d.id};});}
 async reviewDocument(i:any){return this.prisma.$transaction(async tx=>{await this.assertReview(tx,i.solicitudId);const u=await tx.documentoCredito.updateMany({where:{id:i.documentoId,solicitudId:i.solicitudId},data:{estado:i.estado,observaciones:this.text(i.observaciones),revisadoPorId:i.actorId,revisadoEn:new Date(),version:{increment:1}}});if(u.count!==1)throw new CreditValidationError('El documento no existe en esta solicitud.');await this.event(tx,i.solicitudId,i.audit);});}
 async reviewRequirement(i:any){return this.prisma.$transaction(async tx=>{await this.assertReview(tx,i.solicitudId);const u=await tx.solicitudCreditoRequisito.updateMany({where:{id:i.requisitoId,solicitudId:i.solicitudId},data:{estado:i.estado,observaciones:this.text(i.observaciones),revisadoPorId:i.actorId,revisadoEn:new Date(),version:{increment:1}}});if(u.count!==1)throw new CreditValidationError('El requisito no existe en esta solicitud.');await this.event(tx,i.solicitudId,i.audit);});}
 async getReadiness(id:number):Promise<CreditReadiness>{const [reqs,refs,docs]=await Promise.all([this.prisma.solicitudCreditoRequisito.findMany({where:{solicitudId:id},select:{obligatorio:true,estado:true}}),this.prisma.referenciaCredito.findMany({where:{solicitudId:id},select:{resultado:true}}),this.prisma.documentoCredito.findMany({where:{solicitudId:id},select:{estado:true}})]);const mandatory=reqs.filter(x=>x.obligatorio);return{requisitosObligatorios:mandatory.length,requisitosCumplidos:mandatory.filter(x=>['CUMPLIDO','EXONERADO'].includes(x.estado)).length,requisitosPendientes:mandatory.filter(x=>x.estado==='PENDIENTE').length,requisitosNoCumplidos:mandatory.filter(x=>x.estado==='NO_CUMPLE').length,referencias:refs.length,referenciasPendientes:refs.filter(x=>x.resultado==='PENDIENTE').length,documentos:docs.length,documentosPendientes:docs.filter(x=>x.estado==='PENDIENTE').length};}
 async approve(i:any):Promise<CreditDecisionCommitResult>{const existing=await this.prisma.decisionCredito.findUnique({where:{claveIdempotencia:i.claveIdempotencia},include:{solicitud:{include:{operacionPedido:true}}}});if(existing){if(existing.solicitudId!==i.application.id)throw new CreditIdempotencyConflictError(i.claveIdempotencia);const op=existing.solicitud.operacionPedido;if(!op)throw new CreditValidationError('La decisión repetida no tiene operación de integración.');return{repeated:true,solicitudId:existing.solicitudId,decisionId:existing.id,creditoId:existing.solicitud.creditoId,decisionType:existing.tipo as any,integrationOperationId:op.id,integrationState:op.estado as any};}if(!i.application.id)throw new Error('Solicitud sin id.');return this.prisma.$transaction(async tx=>{const app=await tx.solicitudCredito.findUniqueOrThrow({where:{id:i.application.id!}});if(app.estado!=='EN_REVISION')throw new CreditAlreadyDecidedError(app.id);const upd=await tx.solicitudCredito.updateMany({where:{id:app.id,version:i.expectedVersion,estado:'EN_REVISION'},data:{estado:'APROBADA',resueltaEn:new Date(),version:{increment:1}}});if(upd.count!==1)throw new CreditConcurrentModificationError({id:app.id});const financed=new Prisma.Decimal(i.montoAutorizado).minus(new Prisma.Decimal(i.anticipoRequerido));const credit=await tx.credito.create({data:{empresaId:app.empresaId,clienteId:app.clienteId,montoAutorizado:new Prisma.Decimal(i.montoAutorizado),anticipoRequerido:new Prisma.Decimal(i.anticipoRequerido),montoFinanciado:financed,plazoAutorizadoDias:i.plazoAutorizadoDias,aprobadoPorId:i.actorId,aprobadoEn:new Date(),estado:'ACTIVO',version:0}});await tx.credito.update({where:{id:credit.id},data:{numero:this.creditNumber(credit.id)}});await tx.solicitudCredito.update({where:{id:app.id},data:{creditoId:credit.id}});const decision=await tx.decisionCredito.create({data:{solicitudId:app.id,decididoPorId:i.actorId,tipo:i.tipo,montoAutorizado:new Prisma.Decimal(i.montoAutorizado),plazoAutorizadoDias:i.plazoAutorizadoDias,anticipoRequerido:new Prisma.Decimal(i.anticipoRequerido),observaciones:this.text(i.observaciones),claveIdempotencia:i.claveIdempotencia}});const op=await tx.operacionIntegracionCreditoPedido.create({data:{solicitudId:app.id,pedidoId:app.pedidoId,actorId:i.actorId,tipo:'APROBACION',estado:'PENDIENTE',claveIdempotencia:`credit-order:approval:${app.id}`}});await this.event(tx,app.id,{actorId:i.actorId,tipo:i.tipo==='AJUSTADA'?'APROBADA_AJUSTADA':'APROBADA',detalle:i.tipo==='AJUSTADA'?'Crédito aprobado con condiciones ajustadas.':'Crédito aprobado.',referencia:{tipo:'DECISION_CREDITO',id:decision.id}});await this.event(tx,app.id,{actorId:i.actorId,tipo:'CREDITO_CREADO',detalle:'Crédito concedido creado.',referencia:{tipo:'CREDITO',id:credit.id}});return{repeated:false,solicitudId:app.id,decisionId:decision.id,creditoId:credit.id,decisionType:i.tipo,integrationOperationId:op.id,integrationState:'PENDIENTE'};});}
 async reject(i:any):Promise<CreditDecisionCommitResult>{const existing=await this.prisma.decisionCredito.findUnique({where:{claveIdempotencia:i.claveIdempotencia},include:{solicitud:{include:{operacionPedido:true}}}});if(existing){if(existing.solicitudId!==i.application.id)throw new CreditIdempotencyConflictError(i.claveIdempotencia);const op=existing.solicitud.operacionPedido;if(!op)throw new CreditValidationError('La decisión repetida no tiene operación de integración.');return{repeated:true,solicitudId:existing.solicitudId,decisionId:existing.id,creditoId:null,decisionType:'RECHAZADA',integrationOperationId:op.id,integrationState:op.estado as any};}if(!i.application.id)throw new Error('Solicitud sin id.');return this.prisma.$transaction(async tx=>{const app=await tx.solicitudCredito.findUniqueOrThrow({where:{id:i.application.id!}});if(app.estado!=='EN_REVISION')throw new CreditAlreadyDecidedError(app.id);const upd=await tx.solicitudCredito.updateMany({where:{id:app.id,version:i.expectedVersion,estado:'EN_REVISION'},data:{estado:'RECHAZADA',resueltaEn:new Date(),motivo:i.observaciones,version:{increment:1}}});if(upd.count!==1)throw new CreditConcurrentModificationError({id:app.id});const d=await tx.decisionCredito.create({data:{solicitudId:app.id,decididoPorId:i.actorId,tipo:'RECHAZADA',observaciones:i.observaciones,claveIdempotencia:i.claveIdempotencia}});const op=await tx.operacionIntegracionCreditoPedido.create({data:{solicitudId:app.id,pedidoId:app.pedidoId,actorId:i.actorId,tipo:'RECHAZO',estado:'PENDIENTE',claveIdempotencia:`credit-order:rejection:${app.id}`}});await this.event(tx,app.id,{actorId:i.actorId,tipo:'RECHAZADA',detalle:i.observaciones,referencia:{tipo:'DECISION_CREDITO',id:d.id}});return{repeated:false,solicitudId:app.id,decisionId:d.id,creditoId:null,decisionType:'RECHAZADA',integrationOperationId:op.id,integrationState:'PENDIENTE'};});}
 async cancel(i:any):Promise<CreditDecisionCommitResult>{const existing=await this.prisma.operacionIntegracionCreditoPedido.findUnique({where:{claveIdempotencia:i.claveIdempotencia}});if(existing){if(existing.solicitudId!==i.application.id)throw new CreditIdempotencyConflictError(i.claveIdempotencia);return{repeated:true,solicitudId:existing.solicitudId,decisionId:null,creditoId:null,decisionType:null,integrationOperationId:existing.id,integrationState:existing.estado as any};}if(!i.application.id)throw new Error('Solicitud sin id.');return this.prisma.$transaction(async tx=>{const u=await tx.solicitudCredito.updateMany({where:{id:i.application.id!,version:i.expectedVersion,estado:{in:['PENDIENTE','EN_REVISION']}},data:{estado:'CANCELADA',resueltaEn:i.application.resueltaEn,canceladaEn:i.application.canceladaEn,motivoCancelacion:i.application.motivoCancelacion,version:i.application.version}});if(u.count!==1)throw new CreditConcurrentModificationError({id:i.application.id});const op=await tx.operacionIntegracionCreditoPedido.create({data:{solicitudId:i.application.id!,pedidoId:i.application.pedidoId,actorId:i.actorId,tipo:'RECHAZO',estado:'PENDIENTE',claveIdempotencia:i.claveIdempotencia}});await this.event(tx,i.application.id!,{actorId:i.actorId,tipo:'CANCELADA',detalle:i.application.motivoCancelacion});return{repeated:false,solicitudId:i.application.id!,decisionId:null,creditoId:null,decisionType:null,integrationOperationId:op.id,integrationState:'PENDIENTE'};});}
 async findByApplicationId(id:number):Promise<CreditIntegrationOperation|null>{const r=await this.prisma.operacionIntegracionCreditoPedido.findUnique({where:{solicitudId:id},include:{solicitud:{include:{decision:true}}}});if(!r)return null;return{id:r.id,solicitudId:r.solicitudId,pedidoId:r.pedidoId,empresaId:r.solicitud.empresaId,actorId:r.actorId,tipo:r.tipo as any,estado:r.estado as any,intentos:r.intentos,reason:r.solicitud.motivoCancelacion??r.solicitud.decision?.observaciones??r.solicitud.motivo??null};}
 async findBlockingByOrderId(pedidoId:number):Promise<CreditIntegrationOperation|null>{const r=await this.prisma.operacionIntegracionCreditoPedido.findFirst({where:{pedidoId,estado:{in:['PENDIENTE','FALLIDA']}},orderBy:{creadoEn:'desc'},include:{solicitud:{include:{decision:true}}}});if(!r)return null;return{id:r.id,solicitudId:r.solicitudId,pedidoId:r.pedidoId,empresaId:r.solicitud.empresaId,actorId:r.actorId,tipo:r.tipo as any,estado:r.estado as any,intentos:r.intentos,reason:r.solicitud.motivoCancelacion??r.solicitud.decision?.observaciones??r.solicitud.motivo??null};}
 async markApplied(i:{operationId:number;actorId:number}){return this.prisma.$transaction(async tx=>{const op=await tx.operacionIntegracionCreditoPedido.update({where:{id:i.operationId},data:{estado:'APLICADA',aplicadaEn:new Date(),ultimoError:null,intentos:{increment:1}}});await this.event(tx,op.solicitudId,{actorId:i.actorId,tipo:'INTEGRACION_PEDIDO_APLICADA',detalle:'Integración con Pedido aplicada.',referencia:{tipo:'OPERACION_INTEGRACION_CREDITO_PEDIDO',id:op.id}});});}
 async markFailed(i:{operationId:number;actorId:number;error:string}){return this.prisma.$transaction(async tx=>{const op=await tx.operacionIntegracionCreditoPedido.update({where:{id:i.operationId},data:{estado:'FALLIDA',aplicadaEn:null,ultimoError:i.error,intentos:{increment:1}}});await this.event(tx,op.solicitudId,{actorId:i.actorId,tipo:'INTEGRACION_PEDIDO_FALLIDA',detalle:i.error,referencia:{tipo:'OPERACION_INTEGRACION_CREDITO_PEDIDO',id:op.id}});});}
 private toApplication(r:any){return CreditApplication.rehydrate({id:r.id,numero:r.numero,empresaId:r.empresaId,pedidoId:r.pedidoId,clienteId:r.clienteId,solicitanteId:r.solicitanteId,politicaId:r.politicaId,creditoId:r.creditoId,montoSolicitado:r.montoSolicitado.toFixed(2),plazoDias:r.plazoDias,anticipoPropuesto:r.anticipoPropuesto.toFixed(2),estado:r.estado as any,motivo:r.motivo,solicitadaEn:r.solicitadaEn,enRevisionEn:r.enRevisionEn,resueltaEn:r.resueltaEn,canceladaEn:r.canceladaEn,motivoCancelacion:r.motivoCancelacion,version:r.version,actualizadoEn:r.actualizadoEn});}
 private applicationNumber(id:number){return `SOL-${String(id).padStart(6,'0')}`;} private creditNumber(id:number){return `CRE-${String(id).padStart(6,'0')}`;} private text(v?:string|null){if(v==null)return null;const s=String(v).trim();return s||null;}
 private async event(tx:Prisma.TransactionClient,id:number,a:CreditAuditDraft){await tx.solicitudCreditoEvento.create({data:{solicitudId:id,usuarioId:a.actorId??null,tipo:a.tipo,detalle:a.detalle??null,referenciaTipo:a.referencia?.tipo??null,referenciaId:a.referencia?.id??null}});}
 private async assertOpen(tx:Prisma.TransactionClient,id:number){const r=await tx.solicitudCredito.findUnique({where:{id},select:{estado:true}});if(!r||!['PENDIENTE','EN_REVISION'].includes(r.estado))throw new CreditValidationError('La solicitud ya no permite modificar el expediente.');}
 private async assertReview(tx:Prisma.TransactionClient,id:number){const r=await tx.solicitudCredito.findUnique({where:{id},select:{estado:true}});if(!r||r.estado!=='EN_REVISION')throw new CreditValidationError('La solicitud debe estar EN_REVISION.');}
}
